@extends('layouts.crm', ['title' => 'Reports'])

@section('content')
    <section class="card border-0 shadow-sm mb-4">
        <div class="card-body">
            <form class="row g-2" method="get" action="{{ route('reports.index') }}">
                <div class="col-md-2"><label class="form-label" for="from">From</label><input class="form-control" id="from" name="from" type="date" value="{{ $filters['from'] ?? '' }}"></div>
                <div class="col-md-2"><label class="form-label" for="to">To</label><input class="form-control" id="to" name="to" type="date" value="{{ $filters['to'] ?? '' }}"></div>
                <div class="col-md-2"><label class="form-label" for="owner">Owner / Agent</label><select class="form-select" id="owner" name="owner"><option value="">All permitted</option>@foreach ($owners as $owner)<option value="{{ $owner->id }}" @selected((string) ($filters['owner'] ?? '') === (string) $owner->id)>{{ $owner->name }}</option>@endforeach</select></div>
                <div class="col-md-2"><label class="form-label" for="team">Team</label><select class="form-select" id="team" name="team"><option value="">All permitted</option>@foreach ($teams as $team)<option value="{{ $team->id }}" @selected((string) ($filters['team'] ?? '') === (string) $team->id)>{{ $team->name }}</option>@endforeach</select></div>
                <div class="col-md-2"><label class="form-label" for="lead_status">Lead status</label><select class="form-select" id="lead_status" name="lead_status"><option value="">All</option>@foreach ($leadStatuses as $status)<option value="{{ $status->id }}" @selected((string) ($filters['lead_status'] ?? '') === (string) $status->id)>{{ $status->name }}</option>@endforeach</select></div>
                <div class="col-md-2"><label class="form-label" for="source">Lead source</label><select class="form-select" id="source" name="source"><option value="">All</option>@foreach ($leadSources as $source)<option value="{{ $source->id }}" @selected((string) ($filters['source'] ?? '') === (string) $source->id)>{{ $source->name }}</option>@endforeach</select></div>
                <div class="col-md-2"><label class="form-label" for="stage">Opportunity stage</label><select class="form-select" id="stage" name="stage"><option value="">All</option>@foreach ($stages as $stage)<option value="{{ $stage->id }}" @selected((string) ($filters['stage'] ?? '') === (string) $stage->id)>{{ $stage->name }}</option>@endforeach</select></div>
                <div class="col-md-2"><label class="form-label" for="activity_status">Activity status</label><select class="form-select" id="activity_status" name="activity_status"><option value="">All</option>@foreach (\App\Models\Activity::STATUSES as $status)<option value="{{ $status }}" @selected(($filters['activity_status'] ?? '') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
                <div class="col-md-2"><label class="form-label" for="direction">Call direction</label><select class="form-select" id="direction" name="direction"><option value="">All</option>@foreach (['inbound', 'outbound', 'unknown'] as $direction)<option value="{{ $direction }}" @selected(($filters['direction'] ?? '') === $direction)>{{ ucfirst($direction) }}</option>@endforeach</select></div>
                <div class="col-md-2"><label class="form-label" for="call_status">Call status</label><select class="form-select" id="call_status" name="call_status"><option value="">All</option>@foreach ($callStatuses as $status)<option value="{{ $status }}" @selected(($filters['call_status'] ?? '') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
                <div class="col-md-2 d-flex align-items-end gap-2"><button class="btn btn-primary" type="submit">Apply</button><a class="btn btn-outline-secondary" href="{{ route('reports.index') }}">Reset</a></div>
            </form>
        </div>
    </section>

    <div class="row g-4">
        <div class="col-lg-6"><section class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Lead funnel</h2><table class="table table-sm"><thead><tr><th>Status</th><th class="text-end">Leads</th></tr></thead><tbody>@forelse ($leadFunnel as $statusId => $row)<tr><td>{{ $leadStatuses->firstWhere('id', $statusId)?->name ?? 'Unknown' }}</td><td class="text-end">{{ $row->total }}</td></tr>@empty<tr><td colspan="2" class="text-muted">No leads found.</td></tr>@endforelse</tbody></table></div></section></div>
        <div class="col-lg-6"><section class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Lead source performance</h2><table class="table table-sm"><thead><tr><th>Source</th><th class="text-end">Leads</th></tr></thead><tbody>@forelse ($sourcePerformance as $sourceId => $row)<tr><td>{{ $leadSources->firstWhere('id', $sourceId)?->name ?? 'Unspecified' }}</td><td class="text-end">{{ $row->total }}</td></tr>@empty<tr><td colspan="2" class="text-muted">No leads found.</td></tr>@endforelse</tbody></table></div></section></div>
        <div class="col-lg-6"><section class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Lead aging</h2><table class="table table-sm"><tbody>@foreach ($leadAging as $bucket => $total)<tr><td>{{ $bucket }}</td><td class="text-end">{{ $total }}</td></tr>@endforeach</tbody></table></div></section></div>
        <div class="col-lg-6"><section class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Opportunity pipeline</h2><table class="table table-sm"><thead><tr><th>Stage</th><th>Open</th><th class="text-end">Amount</th></tr></thead><tbody>@forelse ($pipeline as $stageId => $row)<tr><td>{{ $stages->firstWhere('id', $stageId)?->name ?? 'Unknown' }}</td><td>{{ $row->total }}</td><td class="text-end">{{ number_format((float) $row->amount, 2) }}</td></tr>@empty<tr><td colspan="3" class="text-muted">No open opportunities found.</td></tr>@endforelse</tbody></table></div></section></div>
        <div class="col-lg-6"><section class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Won / Lost opportunities</h2><table class="table table-sm"><thead><tr><th>Result</th><th>Count</th><th class="text-end">Amount</th></tr></thead><tbody>@forelse ($wonLost as $status => $row)<tr><td>{{ ucfirst($status) }}</td><td>{{ $row->total }}</td><td class="text-end">{{ number_format((float) $row->amount, 2) }}</td></tr>@empty<tr><td colspan="3" class="text-muted">No closed opportunities found.</td></tr>@endforelse</tbody></table></div></section></div>
        <div class="col-lg-6"><section class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Activity / follow-up report</h2><table class="table table-sm"><thead><tr><th>Status</th><th class="text-end">Activities</th></tr></thead><tbody>@forelse ($activityReport as $status => $row)<tr><td>{{ ucfirst($status) }}</td><td class="text-end">{{ $row->total }}</td></tr>@empty<tr><td colspan="2" class="text-muted">No activities found.</td></tr>@endforelse</tbody></table></div></section></div>
        <div class="col-lg-6"><section class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Call activity report</h2><table class="table table-sm"><thead><tr><th>Direction</th><th>Status</th><th class="text-end">Calls</th></tr></thead><tbody>@forelse ($callReport as $row)<tr><td>{{ ucfirst($row->direction ?: 'unknown') }}</td><td>{{ ucfirst($row->status ?: 'unknown') }}</td><td class="text-end">{{ $row->total }}</td></tr>@empty<tr><td colspan="3" class="text-muted">No calls found.</td></tr>@endforelse</tbody></table></div></section></div>
        <div class="col-12"><section class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Agent performance</h2><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Agent</th><th>Leads</th><th>Opportunities</th><th>Activities</th><th>Calls</th></tr></thead><tbody>@forelse ($agentPerformance as $row)<tr><td>{{ $row['user']->name }}</td><td>{{ $row['leads'] }}</td><td>{{ $row['opportunities'] }}</td><td>{{ $row['activities'] }}</td><td>{{ $row['calls'] }}</td></tr>@empty<tr><td colspan="5" class="text-muted">No permitted agents found.</td></tr>@endforelse</tbody></table></div></div></section></div>
    </div>
@endsection
