<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\Admin\AuditLogController;
use App\Http\Controllers\Admin\CrmSettingsController;
use App\Http\Controllers\Admin\JustCallMonitoringController;
use App\Http\Controllers\Admin\JustCallSettingsController;
use App\Http\Controllers\Admin\JustCallWebhookInboxController;
use App\Http\Controllers\Admin\JustCallUserMappingController;
use App\Http\Controllers\Admin\RolePermissionController;
use App\Http\Controllers\Admin\TeamController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\WorkflowRuleController;
use App\Http\Controllers\Admin\OperationalHealthController;
use App\Http\Controllers\CallLogController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LeadAssignmentController;
use App\Http\Controllers\LeadConversionController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\JustCallWebhookController;
use App\Http\Controllers\JustCallClickToCallController;
use App\Http\Controllers\ModulePlaceholderController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OpportunityController;
use App\Http\Controllers\ImportExportController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\ScreenPopController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('dashboard');
});

Route::post('/webhooks/justcall', JustCallWebhookController::class)->middleware('throttle:justcall-webhook')->name('webhooks.justcall');

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:login')->name('login.store');
});

Route::middleware('auth')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/reports', ReportsController::class)->name('reports.index');
    Route::get('/import-export', [ImportExportController::class, 'index'])->name('import-export.index');
    Route::post('/import-export', [ImportExportController::class, 'import'])->name('import-export.import');
    Route::get('/export/{resource}', [ImportExportController::class, 'export'])->name('import-export.export');
    Route::get('/screen-pop/current', [ScreenPopController::class, 'current'])->name('screen-pop.current');
    Route::post('/screen-pop/{callLog}/dismiss', [ScreenPopController::class, 'dismiss'])->name('screen-pop.dismiss');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::patch('/notifications/{notification}/read', [NotificationController::class, 'markRead'])->name('notifications.mark-read');
    Route::patch('/notifications/read-all', [NotificationController::class, 'markAllRead'])->name('notifications.mark-all-read');
    Route::get('/leads', [LeadController::class, 'index'])->name('leads.index');
    Route::get('/leads/create', [LeadController::class, 'create'])->name('leads.create');
    Route::post('/leads', [LeadController::class, 'store'])->name('leads.store');
    Route::get('/leads/{lead}', [LeadController::class, 'show'])->name('leads.show');
    Route::get('/leads/{lead}/edit', [LeadController::class, 'edit'])->name('leads.edit');
    Route::put('/leads/{lead}', [LeadController::class, 'update'])->name('leads.update');
    Route::post('/leads/{lead}/assign', [LeadAssignmentController::class, 'store'])->name('leads.assign');
    Route::patch('/leads/{lead}/qualify', [LeadConversionController::class, 'qualify'])->name('leads.qualify');
    Route::post('/leads/{lead}/convert', [LeadConversionController::class, 'convert'])->name('leads.convert');
    Route::post('/leads/{lead}/justcall/call', [JustCallClickToCallController::class, 'lead'])->name('leads.justcall.call');
    Route::get('/activities', [ActivityController::class, 'index'])->name('activities.index');
    Route::get('/activities/create', [ActivityController::class, 'create'])->name('activities.create');
    Route::post('/activities', [ActivityController::class, 'store'])->name('activities.store');
    Route::get('/activities/{activity}', [ActivityController::class, 'show'])->name('activities.show');
    Route::get('/activities/{activity}/edit', [ActivityController::class, 'edit'])->name('activities.edit');
    Route::put('/activities/{activity}', [ActivityController::class, 'update'])->name('activities.update');
    Route::patch('/activities/{activity}/complete', [ActivityController::class, 'complete'])->name('activities.complete');
    Route::get('/calls', [CallLogController::class, 'index'])->name('calls.index');
    Route::get('/calls/{callLog}', [CallLogController::class, 'show'])->name('calls.show');
    Route::patch('/calls/{callLog}', [CallLogController::class, 'update'])->name('calls.update');
    Route::get('/calls/{callLog}/recording', [CallLogController::class, 'recording'])->name('calls.recording');
    Route::get('/customers', [CustomerController::class, 'index'])->name('customers.index');
    Route::get('/customers/create', [CustomerController::class, 'create'])->name('customers.create');
    Route::post('/customers', [CustomerController::class, 'store'])->name('customers.store');
    Route::get('/customers/{customer}', [CustomerController::class, 'show'])->name('customers.show');
    Route::get('/customers/{customer}/edit', [CustomerController::class, 'edit'])->name('customers.edit');
    Route::put('/customers/{customer}', [CustomerController::class, 'update'])->name('customers.update');
    Route::post('/customers/{customer}/justcall/call', [JustCallClickToCallController::class, 'customer'])->name('customers.justcall.call');
    Route::get('/contacts', [ContactController::class, 'index'])->name('contacts.index');
    Route::get('/contacts/create', [ContactController::class, 'create'])->name('contacts.create');
    Route::post('/contacts', [ContactController::class, 'store'])->name('contacts.store');
    Route::get('/contacts/{contact}', [ContactController::class, 'show'])->name('contacts.show');
    Route::get('/contacts/{contact}/edit', [ContactController::class, 'edit'])->name('contacts.edit');
    Route::put('/contacts/{contact}', [ContactController::class, 'update'])->name('contacts.update');
    Route::post('/contacts/{contact}/justcall/call', [JustCallClickToCallController::class, 'contact'])->name('contacts.justcall.call');
    Route::get('/opportunities', [OpportunityController::class, 'index'])->name('opportunities.index');
    Route::get('/opportunities/pipeline', [OpportunityController::class, 'pipeline'])->name('opportunities.pipeline');
    Route::get('/opportunities/create', [OpportunityController::class, 'create'])->name('opportunities.create');
    Route::post('/opportunities', [OpportunityController::class, 'store'])->name('opportunities.store');
    Route::get('/opportunities/{opportunity}', [OpportunityController::class, 'show'])->name('opportunities.show');
    Route::get('/opportunities/{opportunity}/edit', [OpportunityController::class, 'edit'])->name('opportunities.edit');
    Route::put('/opportunities/{opportunity}', [OpportunityController::class, 'update'])->name('opportunities.update');
    Route::patch('/opportunities/{opportunity}/stage', [OpportunityController::class, 'changeStage'])->name('opportunities.change-stage');
    Route::get('/admin/users', [UserController::class, 'index'])->name('admin.users.index');
    Route::get('/admin/users/create', [UserController::class, 'create'])->name('admin.users.create');
    Route::post('/admin/users', [UserController::class, 'store'])->name('admin.users.store');
    Route::get('/admin/users/{user}/edit', [UserController::class, 'edit'])->name('admin.users.edit');
    Route::put('/admin/users/{user}', [UserController::class, 'update'])->name('admin.users.update');
    Route::patch('/admin/users/{user}/status', [UserController::class, 'toggleStatus'])->name('admin.users.status');
    Route::get('/admin/roles-permissions', [RolePermissionController::class, 'index'])->name('admin.roles.index');
    Route::get('/admin/teams', [TeamController::class, 'index'])->name('admin.teams.index');
    Route::get('/admin/teams/create', [TeamController::class, 'create'])->name('admin.teams.create');
    Route::post('/admin/teams', [TeamController::class, 'store'])->name('admin.teams.store');
    Route::get('/admin/teams/{team}/edit', [TeamController::class, 'edit'])->name('admin.teams.edit');
    Route::get('/admin/workflows', [WorkflowRuleController::class, 'index'])->name('admin.workflows.index');
    Route::get('/admin/workflows/create', [WorkflowRuleController::class, 'create'])->name('admin.workflows.create');
    Route::post('/admin/workflows', [WorkflowRuleController::class, 'store'])->name('admin.workflows.store');
    Route::get('/admin/workflows/{workflowRule}/edit', [WorkflowRuleController::class, 'edit'])->name('admin.workflows.edit');
    Route::put('/admin/workflows/{workflowRule}', [WorkflowRuleController::class, 'update'])->name('admin.workflows.update');
    Route::patch('/admin/workflows/{workflowRule}/toggle', [WorkflowRuleController::class, 'toggle'])->name('admin.workflows.toggle');
    Route::get('/admin/health', OperationalHealthController::class)->name('admin.health');
    Route::put('/admin/teams/{team}', [TeamController::class, 'update'])->name('admin.teams.update');
    Route::patch('/admin/teams/{team}/status', [TeamController::class, 'toggleStatus'])->name('admin.teams.status');
    Route::get('/admin/crm-settings', [CrmSettingsController::class, 'index'])->name('admin.crm-settings.index');
    Route::get('/admin/crm-settings/{typeKey}', [CrmSettingsController::class, 'show'])->name('admin.crm-settings.show');
    Route::post('/admin/crm-settings/{typeKey}', [CrmSettingsController::class, 'store'])->name('admin.crm-settings.store');
    Route::get('/admin/crm-settings/{typeKey}/{value}/edit', [CrmSettingsController::class, 'edit'])->name('admin.crm-settings.edit');
    Route::put('/admin/crm-settings/{typeKey}/{value}', [CrmSettingsController::class, 'update'])->name('admin.crm-settings.update');
    Route::patch('/admin/crm-settings/{typeKey}/{value}/status', [CrmSettingsController::class, 'toggleStatus'])->name('admin.crm-settings.status');
    Route::get('/admin/audit-logs', [AuditLogController::class, 'index'])->name('admin.audit-logs.index');
    Route::get('/admin/justcall-settings', [JustCallSettingsController::class, 'index'])->name('admin.justcall-settings.index');
    Route::post('/admin/justcall-settings/test', [JustCallSettingsController::class, 'test'])->name('admin.justcall-settings.test');
    Route::get('/admin/justcall-settings/monitoring', [JustCallMonitoringController::class, 'index'])->name('admin.justcall-monitoring.index');
    Route::get('/admin/justcall-settings/monitoring/reconcile', [JustCallMonitoringController::class, 'reconcile'])->name('admin.justcall-monitoring.reconcile');
    Route::post('/admin/justcall-settings/monitoring/reconcile', [JustCallMonitoringController::class, 'storeReconciliation'])->name('admin.justcall-monitoring.reconcile.store');
    Route::post('/admin/justcall-settings/monitoring/reprocess', [JustCallMonitoringController::class, 'reprocess'])->name('admin.justcall-monitoring.reprocess');
    Route::get('/admin/justcall-settings/webhook-inbox', [JustCallWebhookInboxController::class, 'index'])->name('admin.justcall-webhooks.index');
    Route::post('/admin/justcall-settings/webhook-inbox/process', [JustCallWebhookInboxController::class, 'processPending'])->name('admin.justcall-webhooks.process');
    Route::get('/admin/justcall-settings/mappings', [JustCallUserMappingController::class, 'index'])->name('admin.justcall-mappings.index');
    Route::post('/admin/justcall-settings/mappings/fetch', [JustCallUserMappingController::class, 'fetch'])->name('admin.justcall-mappings.fetch');
    Route::post('/admin/justcall-settings/mappings', [JustCallUserMappingController::class, 'store'])->name('admin.justcall-mappings.store');
    Route::put('/admin/justcall-settings/mappings/{mapping}', [JustCallUserMappingController::class, 'update'])->name('admin.justcall-mappings.update');
    Route::patch('/admin/justcall-settings/mappings/{mapping}/disable', [JustCallUserMappingController::class, 'disable'])->name('admin.justcall-mappings.disable');
    Route::post('/admin/justcall-settings/mappings/{mapping}/verify', [JustCallUserMappingController::class, 'verify'])->name('admin.justcall-mappings.verify');
    Route::get('/module/{module}', ModulePlaceholderController::class)->name('modules.placeholder');
});
